config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :events
  resources :invitations
  root to: 'sessions#welcome'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get '/logout', to: "sessions#destroy"
  get 'events/:id/invitations/new', to: "invitations#new"
  post '/invitations/accept/:id', to: "invitations#accept"
  post '/invitations/decline/:id', to: "invitations#decline"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"

    has_many :event_attendances, foreign_key: :attended_event_id, dependent: :destroy
    has_many :attendees, through: :event_attendances, source: :attendee

    
    has_many :invitations

    validates :event_name, presence:true
    validates :event_date, presence:true
    validates :location, presence:true

    def self.passed_events(time)
        where("event_date < ?", time)
    end

    def self.upcoming_events(time)
        where("event_date > ?", time)
    end
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
    belongs_to :attended_event, class_name: "Event"
    belongs_to :attendee, class_name: "User"
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :event
    belongs_to :receiver, class_name: "User"

    validates :receiver_id, presence:true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :created_events, foreign_key: :creator_id, class_name: "Event"

    has_many :event_attendances, foreign_key: :attendee_id, dependent: :destroy
    has_many :attended_events, through: :event_attendances, dependent: :destroy


    has_many :received_invitations, foreign_key: :receiver_id, class_name: "Invitation"
    has_many :senders, through: :received_invitations

    validates :username, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :logged_in?
    before_action :authorized
    
    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def authorized
        if !logged_in?
            flash[:error] = "Please login"
            redirect_to '/login' 
        end
     end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController


    def index
        @events = Event.all
    end
    
    def show
        @event = Event.find(params[:id])    
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.created_events.create(event_params)

        if @event.save
            flash[:success] = "Event created successfully!"
            redirect_to event_path(@event)
        else
            flash[:error] = "Event could not be created"
            render 'new'
        end
    end

 
    

    private
    def event_params
        params.require(:event).permit(:event_date, :event_name, :event_description, :location)
    end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
    def new
        @event = Event.find(params[:id])
        @invitation = @event.invitations.build
        @users = User.all
    end

    def create
        @invitation = Invitation.new(invitation_params)

        if @invitation.save
            flash[:success] = "Invitation has been sent successfully"
            redirect_to root_path
        else
            flash[:error] = "Invitation could not be sent"
            render 'new'
        end
    end

    def accept
        @invitation = Invitation.find(params[:id])
        @invitation.event.attendees << current_user
        @invitation.destroy
        flash[:success] = 'Invitation Accepted.'
        redirect_to root_path
    end

    def decline
        @invitation = Invitation.find(params[:id])
        @invitation.destroy
        flash[:error] = 'Invitation Declined.'
        redirect_to root_path
    end



    private
    def invitation_params
        params.require(:invitation).permit(:receiver_id, :event_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authorized, only: [:new, :create, :welcome]


    def new
    end
  
    def create
      @user = User.find_by(username: params[:username])
        if @user 
            session[:user_id] = @user.id
            redirect_to '/welcome'
        else
            redirect_to '/login'
        end
    end
  
    def login
    end
  
    def welcome
        @events = Event.all
    end
  
    def destroy
        session[:user_id] = nil
        redirect_to '/welcome'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]

    def index
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to '/welcome'
        else
            render 'new'
        end
    end
    private
    def user_params
        params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/new.html.erb
<h1> New Event </h1>

<%= form_for @event do |f|%>
    <%= f.label 'Event Name:', class: "form-label"%></br>
    <%= f.text_field :event_name, class: "form-input"%></br>
    <%= f.label 'Event Date:', class: "form-label"%></br>
    <%= f.datetime_field :event_date, class: "form-input"%></br>
    <%= f.label 'Event Location:',  class: "form-label"%></br>
    <%= f.text_field :location, class: "form-input"%></br>
    <%= f.label 'Event Description:',  class: "form-label"%></br>
    <%= f.text_area :event_description, class: "form-input"%></br>
    <%= f.submit "Create Event", class: "form-button"%>
<%end%>

<%= link_to '<< Back', root_path %>

app/views/events/show.html.erb
<div class = "event">
    <div class = "event-container">
        <% if current_user.id == @event.creator_id%>
            <%= link_to '+ Send Invitation', { controller: 'invitations', action: 'new', id: @event.id}, class: "new-event-link"%>
        <%end%>
        <h2>Event Name: <%= @event.event_name %></h2>
        <h3><img src="https://img.icons8.com/android/24/000000/calendar.png"/> <%= @event.event_date.to_formatted_s(:long)%></h3>
        <h3><img src="https://img.icons8.com/material-sharp/24/000000/person-male.png"/> Created by: <%= @event.creator.username%></h3>
        <h3><img src="https://img.icons8.com/material/24/000000/worldwide-location--v1.png"/> <%= @event.location%></h3>
        <h4>Attendees</h4>
        <ul>
        <% @event.attendees.each do |attendee|%>
            <li>- <%= attendee.username%></li>
        <%end%>
        </ul>
    </div>
</div>

<%= link_to '<< Back', root_path %>

app/views/invitations/new.html.erb
<h1> New Invitation </h1>

<%= form_for @invitation do |f|%>
    <%= f.hidden_field :event_id, :value => @event.id %>
    <%= f.label 'Receiver ID', class: "form-label"%></br>
    <%= f.number_field :receiver_id, class: "form-input"%></br>
    <%= f.submit 'Submit', class: "form-button"%>
<%end%>

<ul>
    <li> Username - User ID </li>    
    <% @users.each do |u|%>
        <li><%= u.username%> - <%= u.id%></li>
    <%end%>
</ul>


<%= link_to '<< Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Poppins" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
        <div class="logo">
            <%= image_tag ("logo.png"), size: "300x75"%>
        </div>
        <ul class="nav-links">
          <% if logged_in?%>
            <li><%= link_to 'Log Out', logout_path, method: :get%></li>
          <%else%>
            <li><%= link_to 'Sign Up', new_user_path %></li>
            <li><%= link_to 'Log In', login_path, method: :get%></li>
          <%end%>
        </ul>
    </nav>
    <% flash.each do |type, msg| %>
      <div class = "<%=type%>">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
    <footer>
      <h3>© 2020 Efe Bikmaz </h3>
      <a href= #>GitHub</a>
    </footer>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
    <%=f.label "Username:"%></br>
    <%=f.text_field :username%></br>
    <%=f.submit 'Sign Up'%>
<%end%>